name: Data Fetcher V5

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  pause-job:
    runs-on: ubuntu-latest
    environment:
      name: wait-1140
      deployment: false
    steps:
      - name: Wait time end
        run: echo "End of waiting. Beginning logging."

  log_data:
    needs:
      pause-job

    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install requests

    - name: Initialize stuff
      run: |
        git config --global user.name "Data-Logger-Bot"
        git config --global user.email "bot@github.com"

      # First run

    - name: Run script (1)
      run: python script.py

    - name: Push data file (1)
      run: |
        git add data/data.txt
        git commit -m "Data update" || exit 0
        git push


      # Second run

    - name: Run script (2)
      run: python script.py

    - name: Push data file (2)
      run: |
        git add data/data.txt
        git commit -m "Data update" || exit 0
        git push







